version: '3.8'
services:
  reverseproxy:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: reverseproxy
    hostname: reverseproxy
    tty: true
    environment:
      TZ: Asia/Tokyo
    restart: always
    ports:
      - 80:80
    volumes:
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
      - reverseproxy:/var/log/nginx

  dog-server:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: dog-server
    hostname: dog-server
    tty: true
    environment:
      TZ: Asia/Tokyo
    restart: always
    ports:
      - 7000:80
    volumes:
      - ./dog-server:/usr/share/nginx/html

  cat-server:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: cat-server
    hostname: cat-server
    tty: true
    environment:
      TZ: Asia/Tokyo
    restart: always
    volumes:
      - ./cat-server:/usr/share/nginx/html
    ports:
      - 7001:80

volumes:
  reverseproxy:
    driver: local
